language: php

php:
  - 7.3

before_install:
  - pecl channel-update pecl.php.net
  - pecl install ast
install:
  - composer install

before_script: skip
script:
  - ./vendor/bin/phan
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix .

after_success:
  - git commit -a -m "Fix code styles"
  - git push