language: php
php:
  - 7.3
before_install:
  - pecl install ast
  - echo "extension=ast.so" > add-ast.ini
  - phpenv config-add add-ast.ini
install:
  - composer install
before_script: skip
script:
  - ./vendor/bin/phan
after_failure:
  - echo "OH!"